### PR TITLE
CSS updates for icons

### PR DESCRIPTION
**Pull request by NABN00B**
Do test before deployment!

### CODE REVIEW

**Comment by NABN00B** [comment]
Here's a screenshot of what I have in mind for the "Previous releases" section (using a demo webpage).
The 1.16.6 row shows the current look.
image

**Comment by hrydgard** [comment]
Finally got around to trying it :) Seems to work perfectly.

**Comment by hrydgard** [comment]
Hm, I take that back, as soon as I deployed it, some icons got the wrong size :/  So I have to back it out for now. But the download page looked good!

**Comment by NABN00B** [comment]
> Hm, I take that back, as soon as I deployed it, some icons (title bar) got the wrong size :/ So I have to back it out for now. But the download page looked good!

Do you have a screenshot?

**Pull request merged**
